# some headers from nodes.tsv
link_properties:
  - '<link_name>'
  - '<backref>'
  - '<label>'
  - '<target>'
  - '<multiplicity>'
  - '<link_required>'
  - '<link_group_required>'
  - '<group_exclusive>'
